core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("SistemaApp.urls")),
    path("", include("UsuarioApp.urls")),
    path("fabrica/", include("FabricaApp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FabricaApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from utils.helpers import resize_image, crop_image
from .choices import ESTADO_POSTGRADO_CHOICES, ESTADO_PROYECTO_CHOICES
import uuid
import os


def upload_to_documentos(instance, filename):
    if instance.codigo_sir:
        codigo_sir = instance.codigo_sir
    else:
        codigo_sir = f"sin_codigo"
    return f"fabrica/{codigo_sir}/documentos/{filename}"


def picture_path_fabrica(instance, filename):
    random_filename = str(uuid.uuid4())
    extension = os.path.splitext(filename)[1]
    if instance.ficha_fabrica.codigo_sir:
        codigo_sir = instance.ficha_fabrica.codigo_sir
    else:
        codigo_sir = f"sin_codigo_{instance.ficha_fabrica.id}"
    return f"fabrica/{codigo_sir}/img/{random_filename}{extension}"


############ DOCENTES ##############


class AreaAcademica(models.Model):
    area = models.CharField(max_length=100)

    class Meta:
        db_table = "area_academica"

    def __str__(self):
        return self.area


class Rol(models.Model):
    rol = models.CharField(max_length=10, unique=True)

    class Meta:
        db_table = "rol"

    def __str__(self):
        return self.rol


class PostGrado(models.Model):
    titulo = models.CharField(max_length=200)
    estado = models.CharField(
        max_length=45, choices=ESTADO_POSTGRADO_CHOICES, default="TITULADO"
    )

    class Meta:
        db_table = "post_grados"

    def __str__(self):
        return self.estado


class Profesion(models.Model):
    nombre_titulo = models.CharField(max_length=45)
    licenciatura = models.CharField(max_length=60)
    estado = models.CharField(
        max_length=45, choices=ESTADO_POSTGRADO_CHOICES, default="TITULADO"
    )

    class Meta:
        db_table = "profesion"

    def __str__(self):
        return self.nombre_titulo


class Docente(models.Model):
    run = models.CharField(max_length=15)
    nombre = models.CharField(max_length=45)
    apellido_p = models.CharField(max_length=45)
    apellido_m = models.CharField(max_length=45)
    telefono = models.CharField(max_length=45)
    email = models.EmailField(max_length=45)
    area_academica = models.ForeignKey(
        AreaAcademica, on_delete=models.CASCADE, default=1
    )
    roles = models.ManyToManyField(Rol)
    profesiones = models.ManyToManyField(Profesion)
    postgrados = models.ManyToManyField(PostGrado)

    class Meta:
        db_table = "docentes"

    def __str__(self):
        return self.nombre


############ PROYECTOS #################


class TRL(models.Model):
    trl_tipo = models.CharField(max_length=40)
    trl = models.CharField(max_length=70)

    class Meta:
        db_table = "trl"
        ordering = ["id"]

    def __str__(self):
        return self.trl


class Sede(models.Model):
    sede_nombre = models.CharField(max_length=45)

    def __str__(self):
        return self.sede_nombre


###################################################
########## FORMULARIO DE PROYECTOS ###############
###################################################


class FormularioProyectoFabrica(models.Model):
    codigo_sir = models.CharField(max_length=25, blank=True, null=True, default="")
    nombre_propuesta = models.CharField(max_length=200, unique=True)
    fecha_inicio = models.DateField()
    registration_date = models.DateTimeField(auto_now_add=True)
    problema = models.TextField(max_length=200)
    objetivo = models.TextField(max_length=300)
    metodologia = models.TextField(max_length=300)
    docente_id = models.ForeignKey(Docente, on_delete=models.CASCADE)
    bidireccionalidad = models.FileField(upload_to=upload_to_documentos)
    contribucion = models.FileField(upload_to=upload_to_documentos)
    carta_gantt = models.FileField(upload_to=upload_to_documentos)
    sede_id = models.ForeignKey(Sede, on_delete=models.CASCADE)
    empresa = models.CharField(max_length=150)
    estado = models.CharField(
        max_length=20, choices=ESTADO_PROYECTO_CHOICES, default="PROCESO"
    )
    fondos = models.BooleanField(default=False)
    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    class Meta:
        db_table = "formulario_proyecto_fabrica"
        constraints = [
            models.UniqueConstraint(
                fields=["codigo_sir"],
                condition=~Q(codigo_sir=""),
                name="codigo_sir_unico",
            )
        ]

    def __str__(self):
        return self.nombre_propuesta


class FabricaImage(models.Model):
    image = models.ImageField(upload_to=picture_path_fabrica)
    ficha_fabrica = models.ForeignKey(
        FormularioProyectoFabrica, related_name="images", on_delete=models.CASCADE
    )

    def save(self, *args, **kwargs):
        super(FabricaImage, self).save(*args, **kwargs)

        if self.image and os.path.exists(self.image.path):
            resize_image(self.image.path, 500)
            crop_image(self.image.path, 500)


class FormularioProyectoFondos(models.Model):
    problema_oportunidad = models.TextField(max_length=8000)
    solucion_innovadora = models.TextField(max_length=8000)
    plan_trabajo = models.TextField(max_length=8000)
    potencial_comercializacion = models.TextField(max_length=8000)
    trl_id = models.ForeignKey(TRL, on_delete=models.CASCADE)
    proyecto = models.ForeignKey(
        FormularioProyectoFabrica,
        on_delete=models.CASCADE,
        related_name="fondos_proyecto",
    )

    class Meta:
        db_table = "formulario_proyecto_fondos"

templates/pages/ficha/fabrica_lista.html
{% extends 'components/Layout/base_extendido.html' %}
{% load static %}   

{% block head_title %}
    Fabrica 4.0
{% endblock head_title %}

{% block content_main %}  

    {% if object_list %}

        <div class="overflow-x-auto min-h-96"> 
            <table aria-labelledby="tablaReporteExcel" aria-describedby="tablaReporteExcel" class="w-full whitespace-nowrap text-left">
                <colgroup>
                    <col class="w-full sm:w-4/12">
                    <col class="lg:w-4/12">
                    <col class="lg:w-2/12">
                    <col class="lg:w-1/12">
                    <col class="lg:w-1/12">
                </colgroup>
                <thead class="border-b border-white/10 text-sm leading-6 text-white">
                <tr>
                    <th scope="col" class=" py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-10">Código SIR</th>
                    <th scope="col" class=" py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-10">Nombre propuesta</th>
                    <th scope="col" class=" py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-10">Fecha de registro</th>
                    <th scope="col" class=" py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-10">Acciones</th>
                </tr>
                </thead>
                <tbody class="divide-y divide-white/5">

                {% for item in object_list %}

                    <tr>
                        <td class=" py-4 pl-0 pr-8 text-sm leading-6 text-gray-400 md:table-cell lg:pr-10">
                          {{ item.codigo_sir|default:"sin código" }}
                        </td>
                        <td class=" py-4 pl-0 pr-8 text-sm leading-6 text-gray-400 md:table-cell lg:pr-10">
                            {{ item.nombre_propuesta }}
                        </td>
                        <td class=" py-4 pl-0 pr-8 text-sm leading-6 text-gray-400 md:table-cell lg:pr-10">
                            {{ item.registration_date| date }}
                        </td>
                        <td class="py-1 pl-0  text-sm leading-6  md:table-cell">
                            <div class="flex gap-2">
                                <a href="{% url "FabriFichaDetail" item.id %}" class="flex w-12 justify-center rounded-md bg-indigo-500 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 ">
                                    {% include "components/svg/svg_ver.html" %}
                                </a>
                                <a href="{% url 'GeneratePdf' item.id %}" target="_blank" class="flex items-center w-12 justify-center rounded-md bg-orange-300 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-orange-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-400">
                                    {% include "components/svg/svg_descargar.html" %}
                                </a>
                                <a href="{% url "FabriFichaUpdate" item.id %}" class="flex items-center w-12 justify-center rounded-md bg-emerald-500 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-emerald-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600">
                                        {% include "components/svg/svg_editar.html" %}
                                </a>

                                {% if user.profile.position_FK.permission_code != "RESTRICTED" %}

                                    <a href="{% url "FabriFichaDelete" item.id %}" onclick="return confirm('¿Estás seguro de que deseas borrar el proyecto?');" class="flex items-center w-12 justify-center rounded-md bg-red-500 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-red-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600 ">
                                        {% include "components/svg/svg_eliminar.html" %}
                                    </a>

                                {% endif %}
                            </div>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
        </div>

    {% else %}

    <strong>NO HAY REGISTROS</strong>

    {% endif %} 

    {% include 'components/paginador.html' %}

    {% include 'components/mensajes.html' %}  

{% endblock content_main %}

templates/pages/ficha/fabrica_update.html
{% extends 'components/Layout/base_extendido.html' %}
{% load static %} 
{% load tailwind_filters %}

{% block head_title %}
    Fabrica 4.0
{% endblock head_title %}

{% block content_main %}  

    <div class="grid gap-8 container min-h-screen">
        <div class="flex min-h-full flex-col justify-center sm:px-6 lg:px-8">
            <div class="sm:mx-auto sm:w-full sm:max-w-[680px]">
                <div class="bg-white px-6 py-10 shadow rounded-lg sm:px-12"> 
                    <h1 class="max-w-2xl font-bold tracking-tight text-gray-900 text-2xl mb-4">Fábrica 4.0</h1>
                    <form method="post" id="formFabrica"  enctype="multipart/form-data">

                        {% csrf_token %}

                        <h3 class="pb-2 block text-gray-900 text-xl font-bold">1. IDENTIFICACIÓN DEL PROYECTO</h3>

                        <div id="div_codigo_sir" class="mb-3">
                            <label for="{{ proyecto_form.codigo_sir.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.codigo_sir.label }}
                            </label>
                            {{ proyecto_form.codigo_sir }}

                            {% if proyecto_form.codigo_sir.errors %}
                                {% for error in proyecto_form.codigo_sir.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_nombre_propuesta" class="mb-3">
                            <label for="{{ proyecto_form.nombre_propuesta.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.nombre_propuesta.label }}
                            </label>
                            {{ proyecto_form.nombre_propuesta }}

                            {% if proyecto_form.nombre_propuesta.errors %}
                                {% for error in proyecto_form.nombre_propuesta.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_sede_id" class="mb-3">
                            <label for="{{ proyecto_form.sede_id.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.sede_id.label }}
                            </label>
                            {{ proyecto_form.sede_id }}

                            {% if proyecto_form.sede_id.errors %}
                                {% for error in proyecto_form.sede_id.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_fecha_inicio" class="mb-3">
                            <label for="{{ proyecto_form.fecha_inicio.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.fecha_inicio.label }}
                            </label>
                            <input type="date" name="fecha_inicio" value="{{ fecha_inicio }}" class="textinput dateinput block appearance-none w-full border px-4 bg-white text-gray-700 rounded-lg focus:outline-none border-gray-300 leading-normal py-2" required id="id_fecha_inicio">

                            {% if proyecto_form.fecha_inicio.errors %}
                                {% for error in proyecto_form.fecha_inicio.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_empresa" class="mb-3">
                            <label for="{{ proyecto_form.empresa.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.empresa.label }}
                            </label>
                            {{ proyecto_form.empresa }}

                            {% if proyecto_form.empresa.errors %}
                                {% for error in proyecto_form.empresa.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <h4 class="pb-2 block text-gray-900 text-base font-bold">DESCRIPCIÓN DEL PROBLEMA</h4>
                        <hr class="pb-2" >

                        <div id="div_problema" class="mb-3">
                            <label for="{{ proyecto_form.problema.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.problema.label }}
                            </label>
                            {{ proyecto_form.problema }}

                            {% if proyecto_form.problema.errors %}
                                {% for error in proyecto_form.problema.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_objetivo" class="mb-3">
                            <label for="{{ proyecto_form.objetivo.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.objetivo.label }}
                            </label>
                            {{ proyecto_form.objetivo }}

                            {% if proyecto_form.objetivo.errors %}
                                {% for error in proyecto_form.objetivo.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_metodologia" class="mb-3">
                            <label for="{{ proyecto_form.metodologia.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.metodologia.label }}
                            </label>
                            {{ proyecto_form.metodologia }}

                            {% if proyecto_form.metodologia.errors %}
                                {% for error in proyecto_form.metodologia.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <h4 class="pb-2 block text-gray-900 text-base font-bold">PLAN DE PROYECTO</h4>
                        <hr class="pb-2" >
                        <h5 class="pb-2 block text-gray-800 text-sm font-bold">EQUIPO DE TRABAJO</h5>

                        <div id="div_docente_id" class="mb-3">
                            <label for="{{ proyecto_form.docente_id.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.docente_id.label }}
                            </label>
                            {{ proyecto_form.docente_id }}

                            {% if proyecto_form.docente_id.errors %}
                                {% for error in proyecto_form.docente_id.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_bidireccionalidad" class="container-input">
                            <p class="block text-gray-700 text-sm font-bold mb-2">{{ proyecto_form.bidireccionalidad.label }}</p> 
                            {{ proyecto_form.bidireccionalidad }}

                            <label for="{{ proyecto_form.bidireccionalidad.id_for_label }}">
                                {% include "components/svg/svg_subir_archivo.html" %}
                                <span class="iborrainputfile">Seleccionar archivo</span>
                            </label>

                            {% if proyecto_form.bidireccionalidad.errors %}
                                {% for error in proyecto_form.bidireccionalidad.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_contribucion" class="container-input">
                            <p class="block text-gray-700 text-sm font-bold mb-2">{{ proyecto_form.contribucion.label }}</p> 
                            {{ proyecto_form.contribucion }}
                            
                            <label for="{{ proyecto_form.contribucion.id_for_label }}">
                                {% include "components/svg/svg_subir_archivo.html" %}
                                <span class="iborrainputfile">Seleccionar archivo</span>
                            </label>

                            {% if proyecto_form.contribucion.errors %}
                                {% for error in proyecto_form.contribucion.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <h5 class="pb-2 block text-gray-800 text-sm font-bold">DOCUMENTACIÓN</h5>
                        <hr class="pb-2">

                        <div id="div_carta_gantt" class="container-input">
                            <p class="block text-gray-700 text-sm font-bold mb-2">{{ proyecto_form.carta_gantt.label }}</p> 
                            {{ proyecto_form.carta_gantt }}
                            
                            <label for="{{ proyecto_form.carta_gantt.id_for_label }}">
                                {% include "components/svg/svg_subir_archivo.html" %}
                                <span class="iborrainputfile">Seleccionar archivo</span>
                            </label>

                            {% if proyecto_form.carta_gantt.errors %}
                                {% for error in proyecto_form.carta_gantt.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="div_fondos" class="mb-3">
                            <label for="{{ proyecto_form.fondos.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">
                                {{ proyecto_form.fondos.label }}
                            </label>
                            {{ proyecto_form.fondos }}

                            {% if proyecto_form.fondos.errors %}
                                {% for error in proyecto_form.fondos.errors %}
                                    <strong>{{ error }}</strong>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div id="parte2_container" style="display: none;">
                            <h3 class="pb-2 block text-gray-900 text-xl font-bold">2. POSTULACIÓN FONDOS</h3>
                            {{ fondos_form|crispy }}
                        </div>

                        {% include "components/btn/button.html" with button_text="Guardar cambios" %}              

                    </form>
                </div>
            </div>
        </div>

        <div class="flex min-h-full flex-col justify-normal fixed-element">
            <div class="sm:mx-auto sm:w-full sm:max-w-[400px]">
                <div class="bg-white p-6 shadow rounded-lg overflow-y-auto max-h-[600px]"> 
                    <h1 class="max-w-2xl font-bold tracking-tight text-gray-900 text-2xl mb-4">Instrucciones</h1>
                    <div id="placeholderText" class="p-2 border rounded text-gray-700">Nombre de la propuesta</div> 
                </div>
            </div>
        </div>
    </div>


    {% include 'components/mensajes.html' %}  

{% endblock content_main %}

{% block javascript %}

    <script defer src="{% static "js/formulario.js" %}"></script>
    <script defer src="{% static "js/commonForm.js" %}"></script>

{% endblock javascript %}